export const MUTATION_TYPES = {
    SET_ACCOUNT_ID:         'SET_ACCOUNT_ID',
    SET_USER:               'SET_USER',
    SET_CHARACTER_DATA:     'SET_CHARACTER_DATA', 
    SET_INVENTORY:          'SET_INVENTORY', 
    SET_SKILLS_INVENTORY:   'SET_SKILLS_INVENTORY',
    SET_DUNGEONS_LIST:      'SET_DUNGEONS_LIST', 
    LOGOUT_USER:            'LOGOUT_USER', 
    SET_COMPUTED_STATS:     'SET_COMPUTED_STATS', 
    SET_MATCH_DATA:         'SET_MATCH_DATA', 
    SET_SKILLS_EFFECT:      'SET_SKILLS_EFFECT'
}